### ISSUE TITLE
Question about RoI preds

### ISSUE THREAD

**Issue by Teassassin** [HeinzJiao/RoIPoly#1]
Hi, ths for your excellent work!
I discovered that in your code, the forward pass of RoIPoly model uses gt bboxes for RoI feats extraction, while the architecture of the model in the paper contains a object detector.
Here is the forward pass code snippet:
```python
    def forward(self, batched_inputs):
        """
        Forward pass of the model.

        Args:
            batched_inputs (list): A list of batched outputs from `DatasetMapper`.
                Each item in the list is a dictionary containing:
                * image (Tensor): The image in (C, H, W) format.
                * instances (Instances): Ground truth instances.
                * file_name (str): The image file path (e.g., "./datasets/AIcrowd/train/images/....jpg").

        Returns:
            loss_dict (dict) if training, or outputs (dict) if in evaluation mode.
        """
        images, images_whwh = self.preprocess_image(batched_inputs)
        # images_whwh: torch.Tensor of shape [batch_size, 4], [[width, height, width, height], ...]
        if isinstance(images, (list, torch.Tensor)):  # False
            images = nested_tensor_from_tensor_list(images)

        # Feature Extraction.
        src = self.backbone(images.tensor)  # `images.tensor`: torch.Size([batch_size, channels, height, width])
        features = list()        
        for f in self.in_features:  # `self.in_features`: ["p2", "p3", "p4", "p5"]
            feature = src[f]
            features.append(feature)

        # Ground truth bounding boxes preparation (used in training).
        gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
        proposal_boxes, box_lengths = pad_gt_boxes(gt_instances, self.num_proposals, self.device)
        # `proposal_boxes`: torch.Tensor([bs, num_proposals, 4]), absolute coordinates (x1, y1, x2, y2).
        # `box_lengths`: torch.Tensor([bs]), length of boxes for each image.

        # Prediction.
        outputs = self.head(features, proposal_boxes)
        # `outputs` contains dict_keys(['pred_logits', 'pred_coords']):
        # - `outputs['pred_logits']`: shape [bs, num_proposals, num_queries], classification scores.
        # - `outputs['pred_coords']`: shape [bs, num_proposals, num_queries, 2], predicted coordinates.

        if self.training:
            # Get file names for debugging or visualization purposes.
            gt_file_names = [x["file_name"] for x in batched_inputs]

            # Prepare the ground truth targets for the loss function.
            targets = prepare_targets(gt_instances, self.device)
            # `targets`: a dict containing 'coords' (absolute) and 'labels' (class 1 for annotated points, class 0 for padded points).

            # Optionally visualize targets (if required for debugging).
            # visualize_targets(targets, gt_file_names)

            # Compute the loss.
            loss_dict = self.criterion(outputs, targets, box_lengths)
            # Loss dictionary keys: ['loss_coords', 'loss_ce']
            weight_dict = self.criterion.weight_dict
            for k in loss_dict.keys():
                if k in weight_dict:
                    loss_dict[k] *= weight_dict[k]
            # Example loss dictionary:
            # {'loss_ce': tensor(0.0945, device='cuda:0', grad_fn=<MulBackward0>),
            #  'loss_coords': tensor(1.4065, device='cuda:0', grad_fn=<MulBackward0>),
            #  'cardinality_error': tensor(46.5000, device='cuda:0')}

            return loss_dict

        else:
            return outputs
```

I wonder if this would be fixed in the future. Looking forward to your reply. Thank you!

**Comment by HeinzJiao** [comment]
Thank you for your interest in our paper. The manuscript is currently under review, and further clarifications on the detailed architecture during both inference and training will be provided in the final version.

To clarify here, during training, we use the ground truth bounding boxes as proposal boxes. During inference, however, the object detector predicts the building bounding boxes, which are then used as the proposal boxes. The object detector itself is pretrained and remains separate from the training of the main model.

Further details about the pretrained object detector will be shared in our upcoming publication.

Regarding the possibility of integrating the object detector into the training process, I believe it is feasible. However, doing so would significantly increase computational requirements. Given our limited computational resources, we chose not to integrate it with the building delineation task. If you have suggestions for achieving a fully end-to-end approach without increasing computational cost, I would welcome the opportunity to discuss them.

**Comment by Teassassin** [comment]
> Thank you for your interest in our paper. The manuscript is currently under review, and further clarifications on the detailed architecture during both inference and training will be provided in the final version.
> 
> To clarify here, during training, we use the ground truth bounding boxes as proposal boxes. During inference, however, the object detector predicts the building bounding boxes, which are then used as the proposal boxes. The object detector itself is pretrained and remains separate from the training of the main model.
> 
> Further details about the pretrained object detector will be shared in our upcoming publication.
> 
> Regarding the possibility of integrating the object detector into the training process, I believe it is feasible. However, doing so would significantly increase computational requirements. Given our limited computational resources, we chose not to integrate it with the building delineation task. If you have suggestions for achieving a fully end-to-end approach without increasing computational cost, I would welcome the opportunity to discuss them.

Thanks for your reply!
I believe that the details of pretraining object detector is essential for the completeness and rigorousness of the paper, and I am looking forward to your revised version.😊
